"""
Dockerfile Generator Service
스택 설정에 따라 Dockerfile을 자동 생성하는 서비스
"""

import os
import tempfile
import docker
import asyncio
from typing import Dict, List, Optional, Tuple
from datetime import datetime
from app.core.config import settings
import logging

logger = logging.getLogger(__name__)


class DockerfileGenerator:
    """Dockerfile 자동 생성 서비스"""

    def __init__(self):
        self.docker_client = docker.from_env()
        self.base_images = {
            "node": {
                "16": "node:16-alpine",
                "18": "node:18-alpine",
                "20": "node:20-alpine"
            },
            "python": {
                "3.9": "python:3.9-slim",
                "3.10": "python:3.10-slim",
                "3.11": "python:3.11-slim"
            },
            "java": {
                "11": "openjdk:11-jre-slim",
                "17": "openjdk:17-jre-slim",
                "21": "openjdk:21-jre-slim"
            },
            "go": {
                "1.19": "golang:1.19-alpine",
                "1.20": "golang:1.20-alpine",
                "1.21": "golang:1.21-alpine"
            }
        }

    def generate_dockerfile(self, stack_config: Dict, environment_id: str) -> str:
        """스택 설정에 따라 Dockerfile 생성"""

        language = stack_config.get("language", "node")
        version = stack_config.get("version", "18")
        framework = stack_config.get("framework")
        dependencies = stack_config.get("dependencies", [])
        ports = stack_config.get("exposed_ports", [3000])
        env_vars = stack_config.get("environment_variables", {})

        # 베이스 이미지 선택
        base_image = self.base_images.get(language, {}).get(version)
        if not base_image:
            base_image = f"{language}:{version}"

        dockerfile_lines = []

        # 1. 베이스 이미지
        dockerfile_lines.append(f"FROM {base_image}")
        dockerfile_lines.append("")

        # 2. 메타데이터
        dockerfile_lines.append(f"# Generated by KubeDev Auto System")
        dockerfile_lines.append(f"# Environment ID: {environment_id}")
        dockerfile_lines.append(f"# Language: {language} {version}")
        if framework:
            dockerfile_lines.append(f"# Framework: {framework}")
        dockerfile_lines.append(f"# Generated at: {datetime.now().isoformat()}")
        dockerfile_lines.append("")

        # 3. 작업 디렉토리
        dockerfile_lines.append("WORKDIR /workspace")
        dockerfile_lines.append("")

        # 4. 시스템 패키지 설치
        if language == "node":
            dockerfile_lines.extend(self._generate_node_dockerfile(framework, dependencies))
        elif language == "python":
            dockerfile_lines.extend(self._generate_python_dockerfile(framework, dependencies))
        elif language == "java":
            dockerfile_lines.extend(self._generate_java_dockerfile(framework, dependencies))
        elif language == "go":
            dockerfile_lines.extend(self._generate_go_dockerfile(framework, dependencies))

        # 5. VS Code Server 설치
        dockerfile_lines.extend(self._generate_vscode_server_setup())

        # 6. 환경 변수 설정
        if env_vars:
            dockerfile_lines.append("# Environment Variables")
            for key, value in env_vars.items():
                dockerfile_lines.append(f"ENV {key}={value}")
            dockerfile_lines.append("")

        # 7. 포트 노출
        if ports:
            dockerfile_lines.append("# Exposed Ports")
            for port in ports:
                dockerfile_lines.append(f"EXPOSE {port}")
            dockerfile_lines.append("EXPOSE 8080")  # VS Code Server
            dockerfile_lines.append("")

        # 8. 시작 스크립트
        dockerfile_lines.extend(self._generate_startup_script(language, framework))

        return "\n".join(dockerfile_lines)

    def _generate_node_dockerfile(self, framework: Optional[str], dependencies: List[str]) -> List[str]:
        """Node.js용 Dockerfile 생성"""
        lines = []

        # 시스템 패키지 설치
        lines.append("# Install system dependencies")
        lines.append("RUN apk add --no-cache git curl")
        lines.append("")

        # 글로벌 패키지 설치
        global_packages = ["npm", "yarn", "nodemon"]
        if framework == "react":
            global_packages.extend(["create-react-app", "@vitejs/create-react"])
        elif framework == "express":
            global_packages.append("express-generator")
        elif framework == "nest":
            global_packages.append("@nestjs/cli")

        lines.append("# Install global packages")
        lines.append(f"RUN npm install -g {' '.join(global_packages)}")
        lines.append("")

        # package.json 템플릿
        if framework == "react":
            lines.extend(self._generate_react_package_json())
        elif framework == "express":
            lines.extend(self._generate_express_package_json())
        else:
            lines.extend(self._generate_default_node_package_json())

        # 의존성 설치
        if dependencies:
            lines.append("# Install custom dependencies")
            lines.append(f"RUN npm install {' '.join(dependencies)}")
            lines.append("")

        return lines

    def _generate_python_dockerfile(self, framework: Optional[str], dependencies: List[str]) -> List[str]:
        """Python용 Dockerfile 생성"""
        lines = []

        # 시스템 패키지
        lines.append("# Install system dependencies")
        lines.append("RUN apt-get update && apt-get install -y \\")
        lines.append("    git curl wget build-essential \\")
        lines.append("    && rm -rf /var/lib/apt/lists/*")
        lines.append("")

        # pip 업그레이드
        lines.append("# Upgrade pip")
        lines.append("RUN pip install --no-cache-dir --upgrade pip")
        lines.append("")

        # 프레임워크별 의존성
        base_packages = ["jupyter", "ipython", "requests", "python-dotenv"]

        if framework == "django":
            base_packages.extend(["django", "djangorestframework", "django-cors-headers"])
        elif framework == "fastapi":
            base_packages.extend(["fastapi", "uvicorn[standard]", "sqlalchemy", "pydantic"])
        elif framework == "flask":
            base_packages.extend(["flask", "flask-restful", "flask-cors", "flask-sqlalchemy"])
        elif framework == "ml":
            base_packages.extend(["numpy", "pandas", "matplotlib", "seaborn", "scikit-learn", "tensorflow"])

        lines.append("# Install Python packages")
        lines.append(f"RUN pip install --no-cache-dir {' '.join(base_packages)}")

        # 커스텀 의존성
        if dependencies:
            lines.append(f"RUN pip install --no-cache-dir {' '.join(dependencies)}")

        lines.append("")

        return lines

    def _generate_java_dockerfile(self, framework: Optional[str], dependencies: List[str]) -> List[str]:
        """Java용 Dockerfile 생성"""
        lines = []

        # 시스템 패키지
        lines.append("# Install system dependencies")
        lines.append("RUN apt-get update && apt-get install -y \\")
        lines.append("    git curl wget maven gradle \\")
        lines.append("    && rm -rf /var/lib/apt/lists/*")
        lines.append("")

        # 프레임워크별 설정
        if framework == "spring":
            lines.append("# Spring Boot setup")
            lines.append("ENV SPRING_PROFILES_ACTIVE=development")
        elif framework == "maven":
            lines.append("# Maven project setup")
            lines.append("COPY pom.xml* ./")
            lines.append("RUN mvn dependency:go-offline || true")

        lines.append("")
        return lines

    def _generate_go_dockerfile(self, framework: Optional[str], dependencies: List[str]) -> List[str]:
        """Go용 Dockerfile 생성"""
        lines = []

        lines.append("# Install system dependencies")
        lines.append("RUN apk add --no-cache git curl")
        lines.append("")

        lines.append("# Go environment")
        lines.append("ENV GO111MODULE=on")
        lines.append("ENV CGO_ENABLED=0")
        lines.append("")

        if framework == "gin":
            lines.append("# Install Gin framework")
            lines.append("RUN go install github.com/gin-gonic/gin@latest")
        elif framework == "fiber":
            lines.append("# Install Fiber framework")
            lines.append("RUN go install github.com/gofiber/fiber/v2@latest")

        lines.append("")
        return lines

    def _generate_vscode_server_setup(self) -> List[str]:
        """VS Code Server 설치 설정"""
        return [
            "# Install VS Code Server",
            "RUN curl -fsSL https://code-server.dev/install.sh | sh",
            "",
            "# Configure VS Code Server",
            "RUN mkdir -p /workspace/.vscode-server",
            "ENV CODE_SERVER_CONFIG=/workspace/.vscode-server",
            "",
            "# Install common VS Code extensions",
            "RUN code-server --install-extension ms-python.python || true",
            "RUN code-server --install-extension bradlc.vscode-tailwindcss || true",
            "RUN code-server --install-extension esbenp.prettier-vscode || true",
            ""
        ]

    def _generate_startup_script(self, language: str, framework: Optional[str]) -> List[str]:
        """시작 스크립트 생성"""
        lines = []

        lines.append("# Create startup script")
        lines.append("COPY <<EOF /workspace/start.sh")
        lines.append("#!/bin/bash")
        lines.append("")
        lines.append("# Git 저장소 클론 (환경 변수에서 설정)")
        lines.append("if [ ! -z \"$GIT_REPOSITORY\" ]; then")
        lines.append("    echo \"Cloning repository: $GIT_REPOSITORY\"")
        lines.append("    if [ ! -z \"$GIT_BRANCH\" ]; then")
        lines.append("        git clone -b $GIT_BRANCH $GIT_REPOSITORY /workspace/project")
        lines.append("    else")
        lines.append("        git clone $GIT_REPOSITORY /workspace/project")
        lines.append("    fi")
        lines.append("    cd /workspace/project")
        lines.append("else")
        lines.append("    cd /workspace")
        lines.append("fi")
        lines.append("")

        # 언어별 프로젝트 초기 설정
        if language == "node":
            lines.append("# Node.js 프로젝트 설정")
            lines.append("if [ ! -f package.json ]; then")
            if framework == "react":
                lines.append("    npx create-react-app . --template typescript")
            elif framework == "express":
                lines.append("    npm init -y && npm install express")
            else:
                lines.append("    npm init -y")
            lines.append("fi")
            lines.append("npm install || true")

        elif language == "python":
            lines.append("# Python 프로젝트 설정")
            lines.append("if [ ! -f requirements.txt ]; then")
            lines.append("    echo 'fastapi==0.104.1' > requirements.txt")
            lines.append("    echo 'uvicorn[standard]==0.24.0' >> requirements.txt")
            lines.append("fi")
            lines.append("pip install -r requirements.txt || true")

        lines.append("")
        lines.append("# VS Code Server 시작")
        lines.append("echo \"Starting VS Code Server...\"")
        lines.append("exec code-server --bind-addr 0.0.0.0:8080 --auth none --disable-telemetry /workspace")
        lines.append("EOF")
        lines.append("")
        lines.append("RUN chmod +x /workspace/start.sh")
        lines.append("")
        lines.append("CMD [\"/workspace/start.sh\"]")

        return lines

    def _generate_react_package_json(self) -> List[str]:
        """React package.json 템플릿"""
        return [
            "# React package.json template",
            "COPY <<EOF /workspace/package.json",
            "{",
            '  "name": "kubdev-react-app",',
            '  "version": "1.0.0",',
            '  "scripts": {',
            '    "start": "react-scripts start",',
            '    "build": "react-scripts build",',
            '    "test": "react-scripts test",',
            '    "eject": "react-scripts eject"',
            '  },',
            '  "dependencies": {',
            '    "react": "^18.0.0",',
            '    "react-dom": "^18.0.0",',
            '    "react-scripts": "^5.0.0"',
            '  }',
            "}",
            "EOF",
            ""
        ]

    def _generate_express_package_json(self) -> List[str]:
        """Express package.json 템플릿"""
        return [
            "# Express package.json template",
            "COPY <<EOF /workspace/package.json",
            "{",
            '  "name": "kubdev-express-app",',
            '  "version": "1.0.0",',
            '  "scripts": {',
            '    "start": "node server.js",',
            '    "dev": "nodemon server.js"',
            '  },',
            '  "dependencies": {',
            '    "express": "^4.18.0",',
            '    "cors": "^2.8.5",',
            '    "dotenv": "^16.0.0"',
            '  },',
            '  "devDependencies": {',
            '    "nodemon": "^3.0.0"',
            '  }',
            "}",
            "EOF",
            ""
        ]

    def _generate_default_node_package_json(self) -> List[str]:
        """기본 Node.js package.json 템플릿"""
        return [
            "# Default Node.js package.json template",
            "COPY <<EOF /workspace/package.json",
            "{",
            '  "name": "kubdev-node-app",',
            '  "version": "1.0.0",',
            '  "main": "index.js",',
            '  "scripts": {',
            '    "start": "node index.js",',
            '    "dev": "nodemon index.js"',
            '  },',
            '  "dependencies": {},',
            '  "devDependencies": {',
            '    "nodemon": "^3.0.0"',
            '  }',
            "}",
            "EOF",
            ""
        ]

    async def build_and_push_image(
        self,
        environment_id: str,
        dockerfile_content: str,
        stack_config: Dict
    ) -> Tuple[str, bool]:
        """Docker 이미지 빌드 및 푸시"""

        image_name = f"{settings.DOCKER_NAMESPACE}/env-{environment_id}"
        image_tag = f"{image_name}:latest"

        try:
            # 임시 디렉토리 생성
            with tempfile.TemporaryDirectory() as temp_dir:
                dockerfile_path = os.path.join(temp_dir, "Dockerfile")

                # Dockerfile 저장
                with open(dockerfile_path, "w") as f:
                    f.write(dockerfile_content)

                logger.info(f"Building Docker image: {image_tag}")

                # 이미지 빌드 (비동기)
                build_result = await self._build_image_async(temp_dir, image_tag)

                if not build_result:
                    return "", False

                # Docker Hub 로그인 및 푸시
                if settings.DOCKER_USERNAME and settings.DOCKER_PASSWORD:
                    push_result = await self._push_image_async(image_tag)
                    if not push_result:
                        logger.warning(f"Failed to push image {image_tag}, but build succeeded")

                logger.info(f"Successfully built image: {image_tag}")
                return image_tag, True

        except Exception as e:
            logger.error(f"Failed to build image for environment {environment_id}: {str(e)}")
            return "", False

    async def _build_image_async(self, build_context: str, image_tag: str) -> bool:
        """비동기 이미지 빌드"""
        try:
            # Docker 빌드를 별도 스레드에서 실행
            loop = asyncio.get_event_loop()
            build_task = loop.run_in_executor(
                None,
                self._build_image_sync,
                build_context,
                image_tag
            )
            return await build_task
        except Exception as e:
            logger.error(f"Async build failed: {str(e)}")
            return False

    def _build_image_sync(self, build_context: str, image_tag: str) -> bool:
        """동기 이미지 빌드"""
        try:
            self.docker_client.images.build(
                path=build_context,
                tag=image_tag,
                rm=True,
                pull=True,
                nocache=False
            )
            return True
        except docker.errors.BuildError as e:
            logger.error(f"Docker build error: {str(e)}")
            return False
        except Exception as e:
            logger.error(f"Unexpected build error: {str(e)}")
            return False

    async def _push_image_async(self, image_tag: str) -> bool:
        """비동기 이미지 푸시"""
        try:
            # Docker 로그인
            self.docker_client.login(
                username=settings.DOCKER_USERNAME,
                password=settings.DOCKER_PASSWORD,
                registry=settings.DOCKER_REGISTRY
            )

            # 이미지 푸시
            loop = asyncio.get_event_loop()
            push_task = loop.run_in_executor(
                None,
                self._push_image_sync,
                image_tag
            )
            return await push_task
        except Exception as e:
            logger.error(f"Failed to push image {image_tag}: {str(e)}")
            return False

    def _push_image_sync(self, image_tag: str) -> bool:
        """동기 이미지 푸시"""
        try:
            self.docker_client.images.push(image_tag)
            return True
        except Exception as e:
            logger.error(f"Push error: {str(e)}")
            return False

    def validate_stack_config(self, stack_config: Dict) -> Tuple[bool, List[str]]:
        """스택 설정 유효성 검증"""
        errors = []

        # 필수 필드 확인
        required_fields = ["language"]
        for field in required_fields:
            if field not in stack_config:
                errors.append(f"Missing required field: {field}")

        # 지원되는 언어 확인
        language = stack_config.get("language")
        if language and language not in self.base_images:
            errors.append(f"Unsupported language: {language}")

        # 버전 확인
        version = stack_config.get("version")
        if language and version:
            if version not in self.base_images.get(language, {}):
                errors.append(f"Unsupported version {version} for language {language}")

        # 포트 유효성 확인
        ports = stack_config.get("exposed_ports", [])
        if ports:
            for port in ports:
                if not isinstance(port, int) or port < 1 or port > 65535:
                    errors.append(f"Invalid port: {port}")

        return len(errors) == 0, errors

    def get_supported_stacks(self) -> Dict:
        """지원되는 스택 목록 반환"""
        return {
            "languages": list(self.base_images.keys()),
            "frameworks": {
                "node": ["react", "express", "nest", "next"],
                "python": ["django", "fastapi", "flask", "ml"],
                "java": ["spring", "maven", "gradle"],
                "go": ["gin", "fiber", "echo"]
            },
            "base_images": self.base_images
        }